version: "1.0"
type: navigation-item
data:
  path: "services.onepanel.settings"
  text: _("Settings")
  position: 10
  icon: "tune"
  url: "/services/onepanel/settings"
  permissions:
    role:
    - admin
